### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings
  commentId: T:neo_bpsys_wpf.Models.WidgetsWindowSettings
  id: WidgetsWindowSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri
  - neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri
  - neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri
  - neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled
  - neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri
  - neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri
  - neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings
  langs:
  - csharp
  - vb
  name: WidgetsWindowSettings
  nameWithType: WidgetsWindowSettings
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: WidgetsWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 235
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 小组件窗口设置
  example: []
  syntax:
    content: public class WidgetsWindowSettings
    content.vb: Public Class WidgetsWindowSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri
  id: MapBpBgUri
  parent: neo_bpsys_wpf.Models.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: MapBpBgUri
  nameWithType: WidgetsWindowSettings.MapBpBgUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapBpBgUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 237
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? MapBpBgUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property MapBpBgUri As String
  overload: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri*
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri
  id: MapBpV2BgUri
  parent: neo_bpsys_wpf.Models.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: MapBpV2BgUri
  nameWithType: WidgetsWindowSettings.MapBpV2BgUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapBpV2BgUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 238
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? MapBpV2BgUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property MapBpV2BgUri As String
  overload: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri*
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled
  id: IsCampIconBlackVerEnabled
  parent: neo_bpsys_wpf.Models.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: IsCampIconBlackVerEnabled
  nameWithType: WidgetsWindowSettings.IsCampIconBlackVerEnabled
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: IsCampIconBlackVerEnabled
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 239
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public bool IsCampIconBlackVerEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsCampIconBlackVerEnabled As Boolean
  overload: neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled*
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri
  id: BpOverviewBgUri
  parent: neo_bpsys_wpf.Models.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: BpOverviewBgUri
  nameWithType: WidgetsWindowSettings.BpOverviewBgUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BpOverviewBgUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 240
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? BpOverviewBgUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BpOverviewBgUri As String
  overload: neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri*
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri
  id: CurrentBanLockImageUri
  parent: neo_bpsys_wpf.Models.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: CurrentBanLockImageUri
  nameWithType: WidgetsWindowSettings.CurrentBanLockImageUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: CurrentBanLockImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 241
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? CurrentBanLockImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property CurrentBanLockImageUri As String
  overload: neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri*
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri
  id: GlobalBanLockImageUri
  parent: neo_bpsys_wpf.Models.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: GlobalBanLockImageUri
  nameWithType: WidgetsWindowSettings.GlobalBanLockImageUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GlobalBanLockImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 242
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? GlobalBanLockImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property GlobalBanLockImageUri As String
  overload: neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri*
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings
  id: TextSettings
  parent: neo_bpsys_wpf.Models.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: TextSettings
  nameWithType: WidgetsWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 243
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public WidgetsWindowTextSettings TextSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
    content.vb: Public Property TextSettings As WidgetsWindowTextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html#neo_bpsys_wpf_Models_WidgetsWindowSettings_MapBpBgUri
  name: MapBpBgUri
  nameWithType: WidgetsWindowSettings.MapBpBgUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpBgUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html#neo_bpsys_wpf_Models_WidgetsWindowSettings_MapBpV2BgUri
  name: MapBpV2BgUri
  nameWithType: WidgetsWindowSettings.MapBpV2BgUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.MapBpV2BgUri
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html#neo_bpsys_wpf_Models_WidgetsWindowSettings_IsCampIconBlackVerEnabled
  name: IsCampIconBlackVerEnabled
  nameWithType: WidgetsWindowSettings.IsCampIconBlackVerEnabled
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.IsCampIconBlackVerEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html#neo_bpsys_wpf_Models_WidgetsWindowSettings_BpOverviewBgUri
  name: BpOverviewBgUri
  nameWithType: WidgetsWindowSettings.BpOverviewBgUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.BpOverviewBgUri
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html#neo_bpsys_wpf_Models_WidgetsWindowSettings_CurrentBanLockImageUri
  name: CurrentBanLockImageUri
  nameWithType: WidgetsWindowSettings.CurrentBanLockImageUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.CurrentBanLockImageUri
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html#neo_bpsys_wpf_Models_WidgetsWindowSettings_GlobalBanLockImageUri
  name: GlobalBanLockImageUri
  nameWithType: WidgetsWindowSettings.GlobalBanLockImageUri
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.GlobalBanLockImageUri
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html#neo_bpsys_wpf_Models_WidgetsWindowSettings_TextSettings
  name: TextSettings
  nameWithType: WidgetsWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings.TextSettings
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html
  name: WidgetsWindowTextSettings
  nameWithType: WidgetsWindowTextSettings
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
