### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings
  commentId: T:neo_bpsys_wpf.Models.ScoreWindowSettings
  id: ScoreWindowSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  - neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3
  - neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  - neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  - neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled
  - neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  - neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  - neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  langs:
  - csharp
  - vb
  name: ScoreWindowSettings
  nameWithType: ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ScoreWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 157
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 比分窗口设置
  example: []
  syntax:
    content: public class ScoreWindowSettings
    content.vb: Public Class ScoreWindowSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  id: Resolution
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: Resolution
  nameWithType: ScoreWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Resolution
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 159
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public WindowResolution Resolution { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WindowResolution
    content.vb: Public Property Resolution As WindowResolution
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  id: SurScoreBgImageUri
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: SurScoreBgImageUri
  nameWithType: ScoreWindowSettings.SurScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: SurScoreBgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 160
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? SurScoreBgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SurScoreBgImageUri As String
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  id: HunScoreBgImageUri
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: HunScoreBgImageUri
  nameWithType: ScoreWindowSettings.HunScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: HunScoreBgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 161
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? HunScoreBgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property HunScoreBgImageUri As String
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  id: GlobalScoreBgImageUri
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: GlobalScoreBgImageUri
  nameWithType: ScoreWindowSettings.GlobalScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GlobalScoreBgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 162
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? GlobalScoreBgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property GlobalScoreBgImageUri As String
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3
  id: GlobalScoreBgImageUriBo3
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: GlobalScoreBgImageUriBo3
  nameWithType: ScoreWindowSettings.GlobalScoreBgImageUriBo3
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GlobalScoreBgImageUriBo3
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 163
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? GlobalScoreBgImageUriBo3 { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property GlobalScoreBgImageUriBo3 As String
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled
  id: IsCampIconBlackVerEnabled
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: IsCampIconBlackVerEnabled
  nameWithType: ScoreWindowSettings.IsCampIconBlackVerEnabled
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: IsCampIconBlackVerEnabled
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 164
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public bool IsCampIconBlackVerEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsCampIconBlackVerEnabled As Boolean
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  id: GlobalScoreTotalMargin
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: GlobalScoreTotalMargin
  nameWithType: ScoreWindowSettings.GlobalScoreTotalMargin
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GlobalScoreTotalMargin
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 165
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public double GlobalScoreTotalMargin { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property GlobalScoreTotalMargin As Double
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  id: TextSettings
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: TextSettings
  nameWithType: ScoreWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 166
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public ScoreWindowTextSettings TextSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.ScoreWindowTextSettings
    content.vb: Public Property TextSettings As ScoreWindowTextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_Resolution
  name: Resolution
  nameWithType: ScoreWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
- uid: neo_bpsys_wpf.Models.WindowResolution
  commentId: T:neo_bpsys_wpf.Models.WindowResolution
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WindowResolution.html
  name: WindowResolution
  nameWithType: WindowResolution
  fullName: neo_bpsys_wpf.Models.WindowResolution
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_SurScoreBgImageUri
  name: SurScoreBgImageUri
  nameWithType: ScoreWindowSettings.SurScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_HunScoreBgImageUri
  name: HunScoreBgImageUri
  nameWithType: ScoreWindowSettings.HunScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_GlobalScoreBgImageUri
  name: GlobalScoreBgImageUri
  nameWithType: ScoreWindowSettings.GlobalScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_GlobalScoreBgImageUriBo3
  name: GlobalScoreBgImageUriBo3
  nameWithType: ScoreWindowSettings.GlobalScoreBgImageUriBo3
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUriBo3
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_IsCampIconBlackVerEnabled
  name: IsCampIconBlackVerEnabled
  nameWithType: ScoreWindowSettings.IsCampIconBlackVerEnabled
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.IsCampIconBlackVerEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_GlobalScoreTotalMargin
  name: GlobalScoreTotalMargin
  nameWithType: ScoreWindowSettings.GlobalScoreTotalMargin
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_TextSettings
  name: TextSettings
  nameWithType: ScoreWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.ScoreWindowTextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html
  name: ScoreWindowTextSettings
  nameWithType: ScoreWindowTextSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings
