### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.GameDataWindowTextSettings
  id: GameDataWindowTextSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData
  - neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName
  langs:
  - csharp
  - vb
  name: GameDataWindowTextSettings
  nameWithType: GameDataWindowTextSettings
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GameDataWindowTextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 206
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 赛后数据窗口文本设置
  example: []
  syntax:
    content: public class GameDataWindowTextSettings
    content.vb: Public Class GameDataWindowTextSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName
  id: TeamName
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: TeamName
  nameWithType: GameDataWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TeamName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 208
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings TeamName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property TeamName As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName*
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints
  id: MinorPoints
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: MinorPoints
  nameWithType: GameDataWindowTextSettings.MinorPoints
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MinorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 211
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MinorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MinorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints*
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints
  id: MajorPoints
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: MajorPoints
  nameWithType: GameDataWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MajorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 214
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MajorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MajorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints*
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId
  id: PlayerId
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: PlayerId
  nameWithType: GameDataWindowTextSettings.PlayerId
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: PlayerId
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 216
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings PlayerId { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property PlayerId As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId*
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName
  id: MapName
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: MapName
  nameWithType: GameDataWindowTextSettings.MapName
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 219
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MapName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MapName As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName*
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress
  id: GameProgress
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: GameProgress
  nameWithType: GameDataWindowTextSettings.GameProgress
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GameProgress
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 222
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings GameProgress { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property GameProgress As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress*
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData
  id: SurData
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: SurData
  nameWithType: GameDataWindowTextSettings.SurData
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: SurData
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 225
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings SurData { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property SurData As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData*
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData
  id: HunData
  parent: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  langs:
  - csharp
  - vb
  name: HunData
  nameWithType: GameDataWindowTextSettings.HunData
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: HunData
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 228
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings HunData { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property HunData As TextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_TeamName
  name: TeamName
  nameWithType: GameDataWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.TeamName
- uid: neo_bpsys_wpf.Models.TextSettings
  commentId: T:neo_bpsys_wpf.Models.TextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.TextSettings.html
  name: TextSettings
  nameWithType: TextSettings
  fullName: neo_bpsys_wpf.Models.TextSettings
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_MinorPoints
  name: MinorPoints
  nameWithType: GameDataWindowTextSettings.MinorPoints
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MinorPoints
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_MajorPoints
  name: MajorPoints
  nameWithType: GameDataWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MajorPoints
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_PlayerId
  name: PlayerId
  nameWithType: GameDataWindowTextSettings.PlayerId
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.PlayerId
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_MapName
  name: MapName
  nameWithType: GameDataWindowTextSettings.MapName
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.MapName
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_GameProgress
  name: GameProgress
  nameWithType: GameDataWindowTextSettings.GameProgress
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.GameProgress
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_SurData
  name: SurData
  nameWithType: GameDataWindowTextSettings.SurData
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.SurData
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html#neo_bpsys_wpf_Models_GameDataWindowTextSettings_HunData
  name: HunData
  nameWithType: GameDataWindowTextSettings.HunData
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings.HunData
