### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  commentId: T:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  id: ITextSettingsNavigationService
  parent: neo_bpsys_wpf.Abstractions.Services
  children:
  - neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  - neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  - neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  langs:
  - csharp
  - vb
  name: ITextSettingsNavigationService
  nameWithType: ITextSettingsNavigationService
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  type: Interface
  source:
    remote:
      path: neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ITextSettingsNavigationService
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
    startLine: 11
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Abstractions.Services
  syntax:
    content: public interface ITextSettingsNavigationService
    content.vb: Public Interface ITextSettingsNavigationService
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  commentId: M:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  id: Close(neo_bpsys_wpf.Enums.FrontWindowType)
  parent: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  langs:
  - csharp
  - vb
  name: Close(FrontWindowType)
  nameWithType: ITextSettingsNavigationService.Close(FrontWindowType)
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  type: Method
  source:
    remote:
      path: neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Close
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
    startLine: 17
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Abstractions.Services
  summary: 关闭设置
  example: []
  syntax:
    content: void Close(FrontWindowType windowType)
    parameters:
    - id: windowType
      type: neo_bpsys_wpf.Enums.FrontWindowType
      description: ''
    content.vb: Sub Close(windowType As FrontWindowType)
  overload: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close*
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  commentId: M:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  id: Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  parent: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  langs:
  - csharp
  - vb
  name: Navigate(FrontWindowType, object)
  nameWithType: ITextSettingsNavigationService.Navigate(FrontWindowType, object)
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType, object)
  type: Method
  source:
    remote:
      path: neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Navigate
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
    startLine: 23
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Abstractions.Services
  summary: 导航到设置
  example: []
  syntax:
    content: void Navigate(FrontWindowType type, object page)
    parameters:
    - id: type
      type: neo_bpsys_wpf.Enums.FrontWindowType
      description: 窗口类型
    - id: page
      type: System.Object
      description: 页面实例
    content.vb: Sub Navigate(type As FrontWindowType, page As Object)
  overload: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate*
  nameWithType.vb: ITextSettingsNavigationService.Navigate(FrontWindowType, Object)
  fullName.vb: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType, Object)
  name.vb: Navigate(FrontWindowType, Object)
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  commentId: M:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  id: SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  parent: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  langs:
  - csharp
  - vb
  name: SetFrameControl(FrontWindowType, Frame)
  nameWithType: ITextSettingsNavigationService.SetFrameControl(FrontWindowType, Frame)
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType, System.Windows.Controls.Frame)
  type: Method
  source:
    remote:
      path: neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: SetFrameControl
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Abstractions/Services/ITextSettingsNavigationService.cs
    startLine: 29
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Abstractions.Services
  summary: 设置Frame控件
  example: []
  syntax:
    content: void SetFrameControl(FrontWindowType windowType, Frame frame)
    parameters:
    - id: windowType
      type: neo_bpsys_wpf.Enums.FrontWindowType
      description: 窗口类型
    - id: frame
      type: System.Windows.Controls.Frame
      description: Frame控件
    content.vb: Sub SetFrameControl(windowType As FrontWindowType, frame As Frame)
  overload: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl*
references:
- uid: neo_bpsys_wpf.Abstractions.Services
  commentId: N:neo_bpsys_wpf.Abstractions.Services
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Abstractions.Services
  nameWithType: neo_bpsys_wpf.Abstractions.Services
  fullName: neo_bpsys_wpf.Abstractions.Services
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions
    name: Abstractions
    href: neo_bpsys_wpf.Abstractions.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions.Services
    name: Services
    href: neo_bpsys_wpf.Abstractions.Services.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions
    name: Abstractions
    href: neo_bpsys_wpf.Abstractions.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions.Services
    name: Services
    href: neo_bpsys_wpf.Abstractions.Services.html
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close*
  commentId: Overload:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close
  href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Close_neo_bpsys_wpf_Enums_FrontWindowType_
  name: Close
  nameWithType: ITextSettingsNavigationService.Close
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close
- uid: neo_bpsys_wpf.Enums.FrontWindowType
  commentId: T:neo_bpsys_wpf.Enums.FrontWindowType
  parent: neo_bpsys_wpf.Enums
  href: neo_bpsys_wpf.Enums.FrontWindowType.html
  name: FrontWindowType
  nameWithType: FrontWindowType
  fullName: neo_bpsys_wpf.Enums.FrontWindowType
- uid: neo_bpsys_wpf.Enums
  commentId: N:neo_bpsys_wpf.Enums
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Enums
  nameWithType: neo_bpsys_wpf.Enums
  fullName: neo_bpsys_wpf.Enums
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Enums
    name: Enums
    href: neo_bpsys_wpf.Enums.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Enums
    name: Enums
    href: neo_bpsys_wpf.Enums.html
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate*
  commentId: Overload:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate
  href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Navigate_neo_bpsys_wpf_Enums_FrontWindowType_System_Object_
  name: Navigate
  nameWithType: ITextSettingsNavigationService.Navigate
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl*
  commentId: Overload:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl
  href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_SetFrameControl_neo_bpsys_wpf_Enums_FrontWindowType_System_Windows_Controls_Frame_
  name: SetFrameControl
  nameWithType: ITextSettingsNavigationService.SetFrameControl
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl
- uid: System.Windows.Controls.Frame
  commentId: T:System.Windows.Controls.Frame
  parent: System.Windows.Controls
  isExternal: true
  name: Frame
  nameWithType: Frame
  fullName: System.Windows.Controls.Frame
- uid: System.Windows.Controls
  commentId: N:System.Windows.Controls
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Windows.Controls
  nameWithType: System.Windows.Controls
  fullName: System.Windows.Controls
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  - name: .
  - uid: System.Windows.Controls
    name: Controls
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.controls
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  - name: .
  - uid: System.Windows.Controls
    name: Controls
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.controls
