### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings
  commentId: T:neo_bpsys_wpf.Models.GameDataWindowSettings
  id: GameDataWindowSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri
  - neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution
  - neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings
  langs:
  - csharp
  - vb
  name: GameDataWindowSettings
  nameWithType: GameDataWindowSettings
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GameDataWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 196
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 赛后数据窗口设置
  example: []
  syntax:
    content: public class GameDataWindowSettings
    content.vb: Public Class GameDataWindowSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution
  id: Resolution
  parent: neo_bpsys_wpf.Models.GameDataWindowSettings
  langs:
  - csharp
  - vb
  name: Resolution
  nameWithType: GameDataWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Resolution
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 198
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public WindowResolution Resolution { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WindowResolution
    content.vb: Public Property Resolution As WindowResolution
  overload: neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution*
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri
  id: BgImageUri
  parent: neo_bpsys_wpf.Models.GameDataWindowSettings
  langs:
  - csharp
  - vb
  name: BgImageUri
  nameWithType: GameDataWindowSettings.BgImageUri
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 199
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? BgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BgImageUri As String
  overload: neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri*
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings
  commentId: P:neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings
  id: TextSettings
  parent: neo_bpsys_wpf.Models.GameDataWindowSettings
  langs:
  - csharp
  - vb
  name: TextSettings
  nameWithType: GameDataWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/MapBpV2
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 200
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public GameDataWindowTextSettings TextSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.GameDataWindowTextSettings
    content.vb: Public Property TextSettings As GameDataWindowTextSettings
  overload: neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution
  href: neo_bpsys_wpf.Models.GameDataWindowSettings.html#neo_bpsys_wpf_Models_GameDataWindowSettings_Resolution
  name: Resolution
  nameWithType: GameDataWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings.Resolution
- uid: neo_bpsys_wpf.Models.WindowResolution
  commentId: T:neo_bpsys_wpf.Models.WindowResolution
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WindowResolution.html
  name: WindowResolution
  nameWithType: WindowResolution
  fullName: neo_bpsys_wpf.Models.WindowResolution
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri
  href: neo_bpsys_wpf.Models.GameDataWindowSettings.html#neo_bpsys_wpf_Models_GameDataWindowSettings_BgImageUri
  name: BgImageUri
  nameWithType: GameDataWindowSettings.BgImageUri
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings.BgImageUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings*
  commentId: Overload:neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings
  href: neo_bpsys_wpf.Models.GameDataWindowSettings.html#neo_bpsys_wpf_Models_GameDataWindowSettings_TextSettings
  name: TextSettings
  nameWithType: GameDataWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings.TextSettings
- uid: neo_bpsys_wpf.Models.GameDataWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.GameDataWindowTextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.GameDataWindowTextSettings.html
  name: GameDataWindowTextSettings
  nameWithType: GameDataWindowTextSettings
  fullName: neo_bpsys_wpf.Models.GameDataWindowTextSettings
