### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  id: CutSceneWindowTextSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress
  - neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId
  - neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints
  - neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName
  - neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId
  - neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName
  langs:
  - csharp
  - vb
  name: CutSceneWindowTextSettings
  nameWithType: CutSceneWindowTextSettings
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: CutSceneWindowTextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 134
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 过场窗口文本设置
  example: []
  syntax:
    content: public class CutSceneWindowTextSettings
    content.vb: Public Class CutSceneWindowTextSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName
  id: TeamName
  parent: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  langs:
  - csharp
  - vb
  name: TeamName
  nameWithType: CutSceneWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TeamName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 136
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings TeamName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property TeamName As TextSettings
  overload: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName*
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints
  id: MajorPoints
  parent: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  langs:
  - csharp
  - vb
  name: MajorPoints
  nameWithType: CutSceneWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MajorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 139
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MajorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MajorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints*
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId
  id: SurPlayerId
  parent: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  langs:
  - csharp
  - vb
  name: SurPlayerId
  nameWithType: CutSceneWindowTextSettings.SurPlayerId
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: SurPlayerId
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 141
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings SurPlayerId { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property SurPlayerId As TextSettings
  overload: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId*
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId
  id: HunPlayerId
  parent: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  langs:
  - csharp
  - vb
  name: HunPlayerId
  nameWithType: CutSceneWindowTextSettings.HunPlayerId
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: HunPlayerId
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 144
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings HunPlayerId { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property HunPlayerId As TextSettings
  overload: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId*
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName
  id: MapName
  parent: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  langs:
  - csharp
  - vb
  name: MapName
  nameWithType: CutSceneWindowTextSettings.MapName
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 147
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MapName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MapName As TextSettings
  overload: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName*
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress
  id: GameProgress
  parent: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  langs:
  - csharp
  - vb
  name: GameProgress
  nameWithType: CutSceneWindowTextSettings.GameProgress
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GameProgress
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 150
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings GameProgress { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property GameProgress As TextSettings
  overload: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName
  href: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.html#neo_bpsys_wpf_Models_CutSceneWindowTextSettings_TeamName
  name: TeamName
  nameWithType: CutSceneWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.TeamName
- uid: neo_bpsys_wpf.Models.TextSettings
  commentId: T:neo_bpsys_wpf.Models.TextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.TextSettings.html
  name: TextSettings
  nameWithType: TextSettings
  fullName: neo_bpsys_wpf.Models.TextSettings
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints
  href: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.html#neo_bpsys_wpf_Models_CutSceneWindowTextSettings_MajorPoints
  name: MajorPoints
  nameWithType: CutSceneWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MajorPoints
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId
  href: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.html#neo_bpsys_wpf_Models_CutSceneWindowTextSettings_SurPlayerId
  name: SurPlayerId
  nameWithType: CutSceneWindowTextSettings.SurPlayerId
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.SurPlayerId
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId
  href: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.html#neo_bpsys_wpf_Models_CutSceneWindowTextSettings_HunPlayerId
  name: HunPlayerId
  nameWithType: CutSceneWindowTextSettings.HunPlayerId
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.HunPlayerId
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName
  href: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.html#neo_bpsys_wpf_Models_CutSceneWindowTextSettings_MapName
  name: MapName
  nameWithType: CutSceneWindowTextSettings.MapName
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.MapName
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress
  href: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.html#neo_bpsys_wpf_Models_CutSceneWindowTextSettings_GameProgress
  name: GameProgress
  nameWithType: CutSceneWindowTextSettings.GameProgress
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.GameProgress
