### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.Settings
  commentId: T:neo_bpsys_wpf.Models.Settings
  id: Settings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.Settings.BpWindowSettings
  - neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  - neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  - neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  - neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: Settings
  fullName: neo_bpsys_wpf.Models.Settings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Settings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 7
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public class Settings
    content.vb: Public Class Settings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: neo_bpsys_wpf.Models.Settings.BpWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.BpWindowSettings
  id: BpWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: BpWindowSettings
  nameWithType: Settings.BpWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.BpWindowSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BpWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 9
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public BpWindowSettings BpWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.BpWindowSettings
    content.vb: Public Property BpWindowSettings As BpWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.BpWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  id: CutSceneWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: CutSceneWindowSettings
  nameWithType: Settings.CutSceneWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: CutSceneWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 10
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public CutSceneWindowSettings CutSceneWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.CutSceneWindowSettings
    content.vb: Public Property CutSceneWindowSettings As CutSceneWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  id: ScoreWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: ScoreWindowSettings
  nameWithType: Settings.ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ScoreWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 11
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public ScoreWindowSettings ScoreWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.ScoreWindowSettings
    content.vb: Public Property ScoreWindowSettings As ScoreWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  id: GameDataWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: GameDataWindowSettings
  nameWithType: Settings.GameDataWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GameDataWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 12
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public GameDataWindowSettings GameDataWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.GameDataWindowSettings
    content.vb: Public Property GameDataWindowSettings As GameDataWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  id: WidgetsWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: WidgetsWindowSettings
  nameWithType: Settings.WidgetsWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: WidgetsWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 13
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public WidgetsWindowSettings WidgetsWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WidgetsWindowSettings
    content.vb: Public Property WidgetsWindowSettings As WidgetsWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.Settings.BpWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.BpWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_BpWindowSettings
  name: BpWindowSettings
  nameWithType: Settings.BpWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.BpWindowSettings
- uid: neo_bpsys_wpf.Models.BpWindowSettings
  commentId: T:neo_bpsys_wpf.Models.BpWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.BpWindowSettings.html
  name: BpWindowSettings
  nameWithType: BpWindowSettings
  fullName: neo_bpsys_wpf.Models.BpWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_CutSceneWindowSettings
  name: CutSceneWindowSettings
  nameWithType: Settings.CutSceneWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings
  commentId: T:neo_bpsys_wpf.Models.CutSceneWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.CutSceneWindowSettings.html
  name: CutSceneWindowSettings
  nameWithType: CutSceneWindowSettings
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_ScoreWindowSettings
  name: ScoreWindowSettings
  nameWithType: Settings.ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings
  commentId: T:neo_bpsys_wpf.Models.ScoreWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html
  name: ScoreWindowSettings
  nameWithType: ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_GameDataWindowSettings
  name: GameDataWindowSettings
  nameWithType: Settings.GameDataWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings
  commentId: T:neo_bpsys_wpf.Models.GameDataWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.GameDataWindowSettings.html
  name: GameDataWindowSettings
  nameWithType: GameDataWindowSettings
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_WidgetsWindowSettings
  name: WidgetsWindowSettings
  nameWithType: Settings.WidgetsWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings
  commentId: T:neo_bpsys_wpf.Models.WidgetsWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html
  name: WidgetsWindowSettings
  nameWithType: WidgetsWindowSettings
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings
