### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  id: WidgetsWindowTextSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress
  - neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints
  - neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName
  - neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord
  - neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName
  - neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord
  - neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName
  langs:
  - csharp
  - vb
  name: WidgetsWindowTextSettings
  nameWithType: WidgetsWindowTextSettings
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: WidgetsWindowTextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 220
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 小组件窗口文本设置
  example: []
  syntax:
    content: public class WidgetsWindowTextSettings
    content.vb: Public Class WidgetsWindowTextSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName
  id: MapBp_MapName
  parent: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  langs:
  - csharp
  - vb
  name: MapBp_MapName
  nameWithType: WidgetsWindowTextSettings.MapBp_MapName
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapBp_MapName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 222
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MapBp_MapName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MapBp_MapName As TextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName*
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord
  id: MapBp_PickWord
  parent: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  langs:
  - csharp
  - vb
  name: MapBp_PickWord
  nameWithType: WidgetsWindowTextSettings.MapBp_PickWord
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapBp_PickWord
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 225
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MapBp_PickWord { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MapBp_PickWord As TextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord*
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord
  id: MapBp_BanWord
  parent: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  langs:
  - csharp
  - vb
  name: MapBp_BanWord
  nameWithType: WidgetsWindowTextSettings.MapBp_BanWord
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapBp_BanWord
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 228
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MapBp_BanWord { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MapBp_BanWord As TextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord*
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName
  id: MapBp_TeamName
  parent: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  langs:
  - csharp
  - vb
  name: MapBp_TeamName
  nameWithType: WidgetsWindowTextSettings.MapBp_TeamName
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapBp_TeamName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 231
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MapBp_TeamName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MapBp_TeamName As TextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName*
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName
  id: BpOverview_TeamName
  parent: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  langs:
  - csharp
  - vb
  name: BpOverview_TeamName
  nameWithType: WidgetsWindowTextSettings.BpOverview_TeamName
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BpOverview_TeamName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 234
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings BpOverview_TeamName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property BpOverview_TeamName As TextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName*
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress
  id: BpOverview_GameProgress
  parent: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  langs:
  - csharp
  - vb
  name: BpOverview_GameProgress
  nameWithType: WidgetsWindowTextSettings.BpOverview_GameProgress
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BpOverview_GameProgress
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 237
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings BpOverview_GameProgress { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property BpOverview_GameProgress As TextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress*
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints
  commentId: P:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints
  id: BpOverview_MinorPoints
  parent: neo_bpsys_wpf.Models.WidgetsWindowTextSettings
  langs:
  - csharp
  - vb
  name: BpOverview_MinorPoints
  nameWithType: WidgetsWindowTextSettings.BpOverview_MinorPoints
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BpOverview_MinorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 240
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings BpOverview_MinorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property BpOverview_MinorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html#neo_bpsys_wpf_Models_WidgetsWindowTextSettings_MapBp_MapName
  name: MapBp_MapName
  nameWithType: WidgetsWindowTextSettings.MapBp_MapName
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_MapName
- uid: neo_bpsys_wpf.Models.TextSettings
  commentId: T:neo_bpsys_wpf.Models.TextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.TextSettings.html
  name: TextSettings
  nameWithType: TextSettings
  fullName: neo_bpsys_wpf.Models.TextSettings
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html#neo_bpsys_wpf_Models_WidgetsWindowTextSettings_MapBp_PickWord
  name: MapBp_PickWord
  nameWithType: WidgetsWindowTextSettings.MapBp_PickWord
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_PickWord
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html#neo_bpsys_wpf_Models_WidgetsWindowTextSettings_MapBp_BanWord
  name: MapBp_BanWord
  nameWithType: WidgetsWindowTextSettings.MapBp_BanWord
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_BanWord
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html#neo_bpsys_wpf_Models_WidgetsWindowTextSettings_MapBp_TeamName
  name: MapBp_TeamName
  nameWithType: WidgetsWindowTextSettings.MapBp_TeamName
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.MapBp_TeamName
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html#neo_bpsys_wpf_Models_WidgetsWindowTextSettings_BpOverview_TeamName
  name: BpOverview_TeamName
  nameWithType: WidgetsWindowTextSettings.BpOverview_TeamName
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_TeamName
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html#neo_bpsys_wpf_Models_WidgetsWindowTextSettings_BpOverview_GameProgress
  name: BpOverview_GameProgress
  nameWithType: WidgetsWindowTextSettings.BpOverview_GameProgress
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_GameProgress
- uid: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints
  href: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.html#neo_bpsys_wpf_Models_WidgetsWindowTextSettings_BpOverview_MinorPoints
  name: BpOverview_MinorPoints
  nameWithType: WidgetsWindowTextSettings.BpOverview_MinorPoints
  fullName: neo_bpsys_wpf.Models.WidgetsWindowTextSettings.BpOverview_MinorPoints
