### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
  commentId: T:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
  id: TextSettingsEditControl.TaskNotifier
  parent: neo_bpsys_wpf.Controls
  children:
  - neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier)~System.Threading.Tasks.Task
  langs:
  - csharp
  - vb
  name: TextSettingsEditControl.TaskNotifier
  nameWithType: TextSettingsEditControl.TaskNotifier
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
  type: Class
  source:
    id: TaskNotifier
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\neo_bpsys_wpf.Controls.TextSettingsEditControl.g.cs
    startLine: 496
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Controls
  summary: A wrapping class that can hold a <xref href="System.Threading.Tasks.Task" data-throw-if-not-resolved="false"></xref> value.
  example: []
  syntax:
    content: protected sealed class TextSettingsEditControl.TaskNotifier
    content.vb: Protected NotInheritable Class TextSettingsEditControl.TaskNotifier
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier)~System.Threading.Tasks.Task
  commentId: M:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier)~System.Threading.Tasks.Task
  id: op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier)~System.Threading.Tasks.Task
  parent: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
  langs:
  - csharp
  - vb
  name: implicit operator Task?(TaskNotifier?)
  nameWithType: TextSettingsEditControl.TaskNotifier.implicit operator Task?(TextSettingsEditControl.TaskNotifier?)
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.implicit operator System.Threading.Tasks.Task?(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier?)
  type: Operator
  source:
    id: op_Implicit
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\neo_bpsys_wpf.Controls.TextSettingsEditControl.g.cs
    startLine: 516
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Controls
  summary: Unwraps the <xref href="System.Threading.Tasks.Task" data-throw-if-not-resolved="false"></xref> value stored in the current instance.
  example: []
  syntax:
    content: public static implicit operator Task?(TextSettingsEditControl.TaskNotifier? notifier)
    parameters:
    - id: notifier
      type: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
      description: The input <xref href="neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier%601" data-throw-if-not-resolved="false"></xref> instance.
    return:
      type: System.Threading.Tasks.Task
    content.vb: Public Shared Widening Operator CType(notifier As TextSettingsEditControl.TaskNotifier) As Task
  overload: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.op_Implicit*
  nameWithType.vb: TextSettingsEditControl.TaskNotifier.CType(TextSettingsEditControl.TaskNotifier)
  fullName.vb: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.CType(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier)
  name.vb: CType(TaskNotifier)
references:
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: neo_bpsys_wpf.Controls
  commentId: N:neo_bpsys_wpf.Controls
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Controls
  nameWithType: neo_bpsys_wpf.Controls
  fullName: neo_bpsys_wpf.Controls
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Controls
    name: Controls
    href: neo_bpsys_wpf.Controls.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Controls
    name: Controls
    href: neo_bpsys_wpf.Controls.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
  commentId: T:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
  parent: neo_bpsys_wpf.Controls
  href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  name: TextSettingsEditControl.TaskNotifier<T>
  nameWithType: TextSettingsEditControl.TaskNotifier<T>
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier<T>
  nameWithType.vb: TextSettingsEditControl.TaskNotifier(Of T)
  fullName.vb: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier(Of T)
  name.vb: TextSettingsEditControl.TaskNotifier(Of T)
  spec.csharp:
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl
    name: TextSettingsEditControl
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  - name: .
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
    name: TaskNotifier
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl
    name: TextSettingsEditControl
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  - name: .
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
    name: TaskNotifier
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.op_Implicit*
  commentId: Overload:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.op_Implicit
  name: implicit operator
  nameWithType: TextSettingsEditControl.TaskNotifier.implicit operator
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.implicit operator
  nameWithType.vb: TextSettingsEditControl.TaskNotifier.CType
  fullName.vb: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.CType
  name.vb: CType
  spec.csharp:
  - name: implicit
  - name: " "
  - name: operator
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
  commentId: T:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
  parent: neo_bpsys_wpf.Controls
  href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  name: TextSettingsEditControl.TaskNotifier
  nameWithType: TextSettingsEditControl.TaskNotifier
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
  spec.csharp:
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl
    name: TextSettingsEditControl
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  - name: .
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
    name: TaskNotifier
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.html
  spec.vb:
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl
    name: TextSettingsEditControl
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  - name: .
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier
    name: TaskNotifier
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier.html
