### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.Settings
  commentId: T:neo_bpsys_wpf.Models.Settings
  id: Settings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.Settings.BpWindowSettings
  - neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  - neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  - neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  - neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: Settings
  fullName: neo_bpsys_wpf.Models.Settings
  type: Class
  source:
    id: Settings
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\neo_bpsys_wpf.Models.Settings.g.cs
    startLine: 6
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: A base class for objects of which the properties must be observable.
  example: []
  syntax:
    content: 'public class Settings : ObservableObject, INotifyPropertyChanged, INotifyPropertyChanging'
    content.vb: Public Class Settings Inherits ObservableObject Implements INotifyPropertyChanged, INotifyPropertyChanging
  inheritance:
  - System.Object
  - CommunityToolkit.Mvvm.ComponentModel.ObservableObject
  implements:
  - System.ComponentModel.INotifyPropertyChanged
  - System.ComponentModel.INotifyPropertyChanging
- uid: neo_bpsys_wpf.Models.Settings.BpWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.BpWindowSettings
  id: BpWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: BpWindowSettings
  nameWithType: Settings.BpWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.BpWindowSettings
  type: Property
  source:
    id: BpWindowSettings
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\neo_bpsys_wpf.Models.Settings.g.cs
    startLine: 9
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  example: []
  syntax:
    content: public BpWindowSettings BpWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.BpWindowSettings
    content.vb: Public Property BpWindowSettings As BpWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.BpWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  id: CutSceneWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: CutSceneWindowSettings
  nameWithType: Settings.CutSceneWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  type: Property
  source:
    id: CutSceneWindowSettings
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\neo_bpsys_wpf.Models.Settings.g.cs
    startLine: 31
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  example: []
  syntax:
    content: public CutSceneWindowSettings CutSceneWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.CutSceneWindowSettings
    content.vb: Public Property CutSceneWindowSettings As CutSceneWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  id: ScoreWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: ScoreWindowSettings
  nameWithType: Settings.ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  type: Property
  source:
    id: ScoreWindowSettings
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\neo_bpsys_wpf.Models.Settings.g.cs
    startLine: 53
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  example: []
  syntax:
    content: public ScoreWindowSettings ScoreWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.ScoreWindowSettings
    content.vb: Public Property ScoreWindowSettings As ScoreWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  id: GameDataWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: GameDataWindowSettings
  nameWithType: Settings.GameDataWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  type: Property
  source:
    id: GameDataWindowSettings
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\neo_bpsys_wpf.Models.Settings.g.cs
    startLine: 75
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  example: []
  syntax:
    content: public GameDataWindowSettings GameDataWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.GameDataWindowSettings
    content.vb: Public Property GameDataWindowSettings As GameDataWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings*
- uid: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  commentId: P:neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  id: WidgetsWindowSettings
  parent: neo_bpsys_wpf.Models.Settings
  langs:
  - csharp
  - vb
  name: WidgetsWindowSettings
  nameWithType: Settings.WidgetsWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  type: Property
  source:
    id: WidgetsWindowSettings
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\neo_bpsys_wpf.Models.Settings.g.cs
    startLine: 97
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  example: []
  syntax:
    content: public WidgetsWindowSettings WidgetsWindowSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WidgetsWindowSettings
    content.vb: Public Property WidgetsWindowSettings As WidgetsWindowSettings
  overload: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: CommunityToolkit.Mvvm.ComponentModel.ObservableObject
  commentId: T:CommunityToolkit.Mvvm.ComponentModel.ObservableObject
  parent: CommunityToolkit.Mvvm.ComponentModel
  isExternal: true
  name: ObservableObject
  nameWithType: ObservableObject
  fullName: CommunityToolkit.Mvvm.ComponentModel.ObservableObject
- uid: System.ComponentModel.INotifyPropertyChanged
  commentId: T:System.ComponentModel.INotifyPropertyChanged
  parent: System.ComponentModel
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.componentmodel.inotifypropertychanged
  name: INotifyPropertyChanged
  nameWithType: INotifyPropertyChanged
  fullName: System.ComponentModel.INotifyPropertyChanged
- uid: System.ComponentModel.INotifyPropertyChanging
  commentId: T:System.ComponentModel.INotifyPropertyChanging
  parent: System.ComponentModel
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.componentmodel.inotifypropertychanging
  name: INotifyPropertyChanging
  nameWithType: INotifyPropertyChanging
  fullName: System.ComponentModel.INotifyPropertyChanging
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CommunityToolkit.Mvvm.ComponentModel
  commentId: N:CommunityToolkit.Mvvm.ComponentModel
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/communitytoolkit
  name: CommunityToolkit.Mvvm.ComponentModel
  nameWithType: CommunityToolkit.Mvvm.ComponentModel
  fullName: CommunityToolkit.Mvvm.ComponentModel
  spec.csharp:
  - uid: CommunityToolkit
    name: CommunityToolkit
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/communitytoolkit
  - name: .
  - uid: CommunityToolkit.Mvvm
    name: Mvvm
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/communitytoolkit.mvvm
  - name: .
  - uid: CommunityToolkit.Mvvm.ComponentModel
    name: ComponentModel
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/communitytoolkit.mvvm.componentmodel
  spec.vb:
  - uid: CommunityToolkit
    name: CommunityToolkit
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/communitytoolkit
  - name: .
  - uid: CommunityToolkit.Mvvm
    name: Mvvm
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/communitytoolkit.mvvm
  - name: .
  - uid: CommunityToolkit.Mvvm.ComponentModel
    name: ComponentModel
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/communitytoolkit.mvvm.componentmodel
- uid: System.ComponentModel
  commentId: N:System.ComponentModel
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.ComponentModel
  nameWithType: System.ComponentModel
  fullName: System.ComponentModel
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.ComponentModel
    name: ComponentModel
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.componentmodel
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.ComponentModel
    name: ComponentModel
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.componentmodel
- uid: neo_bpsys_wpf.Models.Settings.BpWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.BpWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_BpWindowSettings
  name: BpWindowSettings
  nameWithType: Settings.BpWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.BpWindowSettings
- uid: neo_bpsys_wpf.Models.BpWindowSettings
  commentId: T:neo_bpsys_wpf.Models.BpWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.BpWindowSettings.html
  name: BpWindowSettings
  nameWithType: BpWindowSettings
  fullName: neo_bpsys_wpf.Models.BpWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_CutSceneWindowSettings
  name: CutSceneWindowSettings
  nameWithType: Settings.CutSceneWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.CutSceneWindowSettings
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings
  commentId: T:neo_bpsys_wpf.Models.CutSceneWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.CutSceneWindowSettings.html
  name: CutSceneWindowSettings
  nameWithType: CutSceneWindowSettings
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_ScoreWindowSettings
  name: ScoreWindowSettings
  nameWithType: Settings.ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.ScoreWindowSettings
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings
  commentId: T:neo_bpsys_wpf.Models.ScoreWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html
  name: ScoreWindowSettings
  nameWithType: ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_GameDataWindowSettings
  name: GameDataWindowSettings
  nameWithType: Settings.GameDataWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.GameDataWindowSettings
- uid: neo_bpsys_wpf.Models.GameDataWindowSettings
  commentId: T:neo_bpsys_wpf.Models.GameDataWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.GameDataWindowSettings.html
  name: GameDataWindowSettings
  nameWithType: GameDataWindowSettings
  fullName: neo_bpsys_wpf.Models.GameDataWindowSettings
- uid: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings*
  commentId: Overload:neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
  href: neo_bpsys_wpf.Models.Settings.html#neo_bpsys_wpf_Models_Settings_WidgetsWindowSettings
  name: WidgetsWindowSettings
  nameWithType: Settings.WidgetsWindowSettings
  fullName: neo_bpsys_wpf.Models.Settings.WidgetsWindowSettings
- uid: neo_bpsys_wpf.Models.WidgetsWindowSettings
  commentId: T:neo_bpsys_wpf.Models.WidgetsWindowSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WidgetsWindowSettings.html
  name: WidgetsWindowSettings
  nameWithType: WidgetsWindowSettings
  fullName: neo_bpsys_wpf.Models.WidgetsWindowSettings
