### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.ScoreWindowTextSettings
  id: ScoreWindowTextSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints
  - neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints
  - neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data
  - neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName
  - neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total
  - neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName
  langs:
  - csharp
  - vb
  name: ScoreWindowTextSettings
  nameWithType: ScoreWindowTextSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ScoreWindowTextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 171
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 分数窗口文本设置
  example: []
  syntax:
    content: public class ScoreWindowTextSettings
    content.vb: Public Class ScoreWindowTextSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints
  id: MinorPoints
  parent: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  langs:
  - csharp
  - vb
  name: MinorPoints
  nameWithType: ScoreWindowTextSettings.MinorPoints
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MinorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 173
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MinorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MinorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints*
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints
  id: MajorPoints
  parent: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  langs:
  - csharp
  - vb
  name: MajorPoints
  nameWithType: ScoreWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MajorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 176
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MajorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MajorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints*
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName
  id: TeamName
  parent: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  langs:
  - csharp
  - vb
  name: TeamName
  nameWithType: ScoreWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TeamName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 179
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings TeamName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property TeamName As TextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName*
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName
  id: ScoreGlobal_TeamName
  parent: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  langs:
  - csharp
  - vb
  name: ScoreGlobal_TeamName
  nameWithType: ScoreWindowTextSettings.ScoreGlobal_TeamName
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ScoreGlobal_TeamName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 182
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings ScoreGlobal_TeamName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property ScoreGlobal_TeamName As TextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName*
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data
  id: ScoreGlobal_Data
  parent: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  langs:
  - csharp
  - vb
  name: ScoreGlobal_Data
  nameWithType: ScoreWindowTextSettings.ScoreGlobal_Data
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ScoreGlobal_Data
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 185
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings ScoreGlobal_Data { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property ScoreGlobal_Data As TextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data*
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total
  id: ScoreGlobal_Total
  parent: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  langs:
  - csharp
  - vb
  name: ScoreGlobal_Total
  nameWithType: ScoreWindowTextSettings.ScoreGlobal_Total
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ScoreGlobal_Total
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 188
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings ScoreGlobal_Total { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property ScoreGlobal_Total As TextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html#neo_bpsys_wpf_Models_ScoreWindowTextSettings_MinorPoints
  name: MinorPoints
  nameWithType: ScoreWindowTextSettings.MinorPoints
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MinorPoints
- uid: neo_bpsys_wpf.Models.TextSettings
  commentId: T:neo_bpsys_wpf.Models.TextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.TextSettings.html
  name: TextSettings
  nameWithType: TextSettings
  fullName: neo_bpsys_wpf.Models.TextSettings
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html#neo_bpsys_wpf_Models_ScoreWindowTextSettings_MajorPoints
  name: MajorPoints
  nameWithType: ScoreWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.MajorPoints
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html#neo_bpsys_wpf_Models_ScoreWindowTextSettings_TeamName
  name: TeamName
  nameWithType: ScoreWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.TeamName
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html#neo_bpsys_wpf_Models_ScoreWindowTextSettings_ScoreGlobal_TeamName
  name: ScoreGlobal_TeamName
  nameWithType: ScoreWindowTextSettings.ScoreGlobal_TeamName
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_TeamName
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html#neo_bpsys_wpf_Models_ScoreWindowTextSettings_ScoreGlobal_Data
  name: ScoreGlobal_Data
  nameWithType: ScoreWindowTextSettings.ScoreGlobal_Data
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Data
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html#neo_bpsys_wpf_Models_ScoreWindowTextSettings_ScoreGlobal_Total
  name: ScoreGlobal_Total
  nameWithType: ScoreWindowTextSettings.ScoreGlobal_Total
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings.ScoreGlobal_Total
