### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings
  commentId: T:neo_bpsys_wpf.Models.ScoreWindowSettings
  id: ScoreWindowSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  - neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  - neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  - neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  - neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  - neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  langs:
  - csharp
  - vb
  name: ScoreWindowSettings
  nameWithType: ScoreWindowSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: ScoreWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 134
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 比分窗口设置
  example: []
  syntax:
    content: public class ScoreWindowSettings
    content.vb: Public Class ScoreWindowSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  id: Resolution
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: Resolution
  nameWithType: ScoreWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Resolution
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 136
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public WindowResolution Resolution { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WindowResolution
    content.vb: Public Property Resolution As WindowResolution
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  id: SurScoreBgImageUri
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: SurScoreBgImageUri
  nameWithType: ScoreWindowSettings.SurScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: SurScoreBgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 137
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? SurScoreBgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SurScoreBgImageUri As String
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  id: HunScoreBgImageUri
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: HunScoreBgImageUri
  nameWithType: ScoreWindowSettings.HunScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: HunScoreBgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 138
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? HunScoreBgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property HunScoreBgImageUri As String
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  id: GlobalScoreBgImageUri
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: GlobalScoreBgImageUri
  nameWithType: ScoreWindowSettings.GlobalScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GlobalScoreBgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 139
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? GlobalScoreBgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property GlobalScoreBgImageUri As String
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  id: GlobalScoreTotalMargin
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: GlobalScoreTotalMargin
  nameWithType: ScoreWindowSettings.GlobalScoreTotalMargin
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GlobalScoreTotalMargin
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 140
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public double GlobalScoreTotalMargin { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property GlobalScoreTotalMargin As Double
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin*
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  commentId: P:neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  id: TextSettings
  parent: neo_bpsys_wpf.Models.ScoreWindowSettings
  langs:
  - csharp
  - vb
  name: TextSettings
  nameWithType: ScoreWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/DeepCustom
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 141
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public ScoreWindowTextSettings TextSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.ScoreWindowTextSettings
    content.vb: Public Property TextSettings As ScoreWindowTextSettings
  overload: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_Resolution
  name: Resolution
  nameWithType: ScoreWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.Resolution
- uid: neo_bpsys_wpf.Models.WindowResolution
  commentId: T:neo_bpsys_wpf.Models.WindowResolution
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WindowResolution.html
  name: WindowResolution
  nameWithType: WindowResolution
  fullName: neo_bpsys_wpf.Models.WindowResolution
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_SurScoreBgImageUri
  name: SurScoreBgImageUri
  nameWithType: ScoreWindowSettings.SurScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.SurScoreBgImageUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_HunScoreBgImageUri
  name: HunScoreBgImageUri
  nameWithType: ScoreWindowSettings.HunScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.HunScoreBgImageUri
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_GlobalScoreBgImageUri
  name: GlobalScoreBgImageUri
  nameWithType: ScoreWindowSettings.GlobalScoreBgImageUri
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreBgImageUri
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_GlobalScoreTotalMargin
  name: GlobalScoreTotalMargin
  nameWithType: ScoreWindowSettings.GlobalScoreTotalMargin
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.GlobalScoreTotalMargin
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
- uid: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings*
  commentId: Overload:neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
  href: neo_bpsys_wpf.Models.ScoreWindowSettings.html#neo_bpsys_wpf_Models_ScoreWindowSettings_TextSettings
  name: TextSettings
  nameWithType: ScoreWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowSettings.TextSettings
- uid: neo_bpsys_wpf.Models.ScoreWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.ScoreWindowTextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.ScoreWindowTextSettings.html
  name: ScoreWindowTextSettings
  nameWithType: ScoreWindowTextSettings
  fullName: neo_bpsys_wpf.Models.ScoreWindowTextSettings
