### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.BpWindowSettings
  commentId: T:neo_bpsys_wpf.Models.BpWindowSettings
  id: BpWindowSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri
  - neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri
  - neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri
  - neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri
  - neo_bpsys_wpf.Models.BpWindowSettings.Resolution
  - neo_bpsys_wpf.Models.BpWindowSettings.TextSettings
  langs:
  - csharp
  - vb
  name: BpWindowSettings
  nameWithType: BpWindowSettings
  fullName: neo_bpsys_wpf.Models.BpWindowSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BpWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 84
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: BP窗口设置
  example: []
  syntax:
    content: public class BpWindowSettings
    content.vb: Public Class BpWindowSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.BpWindowSettings.Resolution
  commentId: P:neo_bpsys_wpf.Models.BpWindowSettings.Resolution
  id: Resolution
  parent: neo_bpsys_wpf.Models.BpWindowSettings
  langs:
  - csharp
  - vb
  name: Resolution
  nameWithType: BpWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.Resolution
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Resolution
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 86
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public WindowResolution Resolution { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WindowResolution
    content.vb: Public Property Resolution As WindowResolution
  overload: neo_bpsys_wpf.Models.BpWindowSettings.Resolution*
- uid: neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri
  commentId: P:neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri
  id: BgImageUri
  parent: neo_bpsys_wpf.Models.BpWindowSettings
  langs:
  - csharp
  - vb
  name: BgImageUri
  nameWithType: BpWindowSettings.BgImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BgImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 87
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? BgImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BgImageUri As String
  overload: neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri*
- uid: neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri
  commentId: P:neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri
  id: CurrentBanLockImageUri
  parent: neo_bpsys_wpf.Models.BpWindowSettings
  langs:
  - csharp
  - vb
  name: CurrentBanLockImageUri
  nameWithType: BpWindowSettings.CurrentBanLockImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: CurrentBanLockImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 88
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? CurrentBanLockImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property CurrentBanLockImageUri As String
  overload: neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri*
- uid: neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri
  commentId: P:neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri
  id: GlobalBanLockImageUri
  parent: neo_bpsys_wpf.Models.BpWindowSettings
  langs:
  - csharp
  - vb
  name: GlobalBanLockImageUri
  nameWithType: BpWindowSettings.GlobalBanLockImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GlobalBanLockImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 89
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? GlobalBanLockImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property GlobalBanLockImageUri As String
  overload: neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri*
- uid: neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri
  commentId: P:neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri
  id: PickingBorderImageUri
  parent: neo_bpsys_wpf.Models.BpWindowSettings
  langs:
  - csharp
  - vb
  name: PickingBorderImageUri
  nameWithType: BpWindowSettings.PickingBorderImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: PickingBorderImageUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 90
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? PickingBorderImageUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property PickingBorderImageUri As String
  overload: neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri*
- uid: neo_bpsys_wpf.Models.BpWindowSettings.TextSettings
  commentId: P:neo_bpsys_wpf.Models.BpWindowSettings.TextSettings
  id: TextSettings
  parent: neo_bpsys_wpf.Models.BpWindowSettings
  langs:
  - csharp
  - vb
  name: TextSettings
  nameWithType: BpWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.TextSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 91
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public BpWindowTextSettings TextSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.BpWindowTextSettings
    content.vb: Public Property TextSettings As BpWindowTextSettings
  overload: neo_bpsys_wpf.Models.BpWindowSettings.TextSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.BpWindowSettings.Resolution*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowSettings.Resolution
  href: neo_bpsys_wpf.Models.BpWindowSettings.html#neo_bpsys_wpf_Models_BpWindowSettings_Resolution
  name: Resolution
  nameWithType: BpWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.Resolution
- uid: neo_bpsys_wpf.Models.WindowResolution
  commentId: T:neo_bpsys_wpf.Models.WindowResolution
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WindowResolution.html
  name: WindowResolution
  nameWithType: WindowResolution
  fullName: neo_bpsys_wpf.Models.WindowResolution
- uid: neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri
  href: neo_bpsys_wpf.Models.BpWindowSettings.html#neo_bpsys_wpf_Models_BpWindowSettings_BgImageUri
  name: BgImageUri
  nameWithType: BpWindowSettings.BgImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.BgImageUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri
  href: neo_bpsys_wpf.Models.BpWindowSettings.html#neo_bpsys_wpf_Models_BpWindowSettings_CurrentBanLockImageUri
  name: CurrentBanLockImageUri
  nameWithType: BpWindowSettings.CurrentBanLockImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.CurrentBanLockImageUri
- uid: neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri
  href: neo_bpsys_wpf.Models.BpWindowSettings.html#neo_bpsys_wpf_Models_BpWindowSettings_GlobalBanLockImageUri
  name: GlobalBanLockImageUri
  nameWithType: BpWindowSettings.GlobalBanLockImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.GlobalBanLockImageUri
- uid: neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri
  href: neo_bpsys_wpf.Models.BpWindowSettings.html#neo_bpsys_wpf_Models_BpWindowSettings_PickingBorderImageUri
  name: PickingBorderImageUri
  nameWithType: BpWindowSettings.PickingBorderImageUri
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.PickingBorderImageUri
- uid: neo_bpsys_wpf.Models.BpWindowSettings.TextSettings*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowSettings.TextSettings
  href: neo_bpsys_wpf.Models.BpWindowSettings.html#neo_bpsys_wpf_Models_BpWindowSettings_TextSettings
  name: TextSettings
  nameWithType: BpWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.BpWindowSettings.TextSettings
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.BpWindowTextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html
  name: BpWindowTextSettings
  nameWithType: BpWindowTextSettings
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings
