### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Services.TextSettingsNavigationService
  commentId: T:neo_bpsys_wpf.Services.TextSettingsNavigationService
  id: TextSettingsNavigationService
  parent: neo_bpsys_wpf.Services
  children:
  - neo_bpsys_wpf.Services.TextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  - neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  - neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  langs:
  - csharp
  - vb
  name: TextSettingsNavigationService
  nameWithType: TextSettingsNavigationService
  fullName: neo_bpsys_wpf.Services.TextSettingsNavigationService
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TextSettingsNavigationService
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
    startLine: 14
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Services
  syntax:
    content: 'public class TextSettingsNavigationService : ITextSettingsNavigationService'
    content.vb: Public Class TextSettingsNavigationService Implements ITextSettingsNavigationService
  inheritance:
  - System.Object
  implements:
  - neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
- uid: neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  commentId: M:neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  id: SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  parent: neo_bpsys_wpf.Services.TextSettingsNavigationService
  langs:
  - csharp
  - vb
  name: SetFrameControl(FrontWindowType, Frame)
  nameWithType: TextSettingsNavigationService.SetFrameControl(FrontWindowType, Frame)
  fullName: neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType, System.Windows.Controls.Frame)
  type: Method
  source:
    remote:
      path: neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: SetFrameControl
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
    startLine: 18
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Services
  summary: 设置Frame控件
  example: []
  syntax:
    content: public void SetFrameControl(FrontWindowType windowType, Frame frame)
    parameters:
    - id: windowType
      type: neo_bpsys_wpf.Enums.FrontWindowType
      description: 窗口类型
    - id: frame
      type: System.Windows.Controls.Frame
      description: Frame控件
    content.vb: Public Sub SetFrameControl(windowType As FrontWindowType, frame As Frame)
  overload: neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl*
  implements:
  - neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
- uid: neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  commentId: M:neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  id: Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  parent: neo_bpsys_wpf.Services.TextSettingsNavigationService
  langs:
  - csharp
  - vb
  name: Navigate(FrontWindowType, object)
  nameWithType: TextSettingsNavigationService.Navigate(FrontWindowType, object)
  fullName: neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType, object)
  type: Method
  source:
    remote:
      path: neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Navigate
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
    startLine: 23
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Services
  summary: 导航到设置
  example: []
  syntax:
    content: public void Navigate(FrontWindowType windowType, object page)
    parameters:
    - id: windowType
      type: neo_bpsys_wpf.Enums.FrontWindowType
    - id: page
      type: System.Object
      description: 页面实例
    content.vb: Public Sub Navigate(windowType As FrontWindowType, page As Object)
  overload: neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate*
  implements:
  - neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  nameWithType.vb: TextSettingsNavigationService.Navigate(FrontWindowType, Object)
  fullName.vb: neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType, Object)
  name.vb: Navigate(FrontWindowType, Object)
- uid: neo_bpsys_wpf.Services.TextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  commentId: M:neo_bpsys_wpf.Services.TextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  id: Close(neo_bpsys_wpf.Enums.FrontWindowType)
  parent: neo_bpsys_wpf.Services.TextSettingsNavigationService
  langs:
  - csharp
  - vb
  name: Close(FrontWindowType)
  nameWithType: TextSettingsNavigationService.Close(FrontWindowType)
  fullName: neo_bpsys_wpf.Services.TextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  type: Method
  source:
    remote:
      path: neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Close
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Services/TextSettingsNavigationService.cs
    startLine: 31
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Services
  summary: 关闭设置
  example: []
  syntax:
    content: public void Close(FrontWindowType windowType)
    parameters:
    - id: windowType
      type: neo_bpsys_wpf.Enums.FrontWindowType
      description: ''
    content.vb: Public Sub Close(windowType As FrontWindowType)
  overload: neo_bpsys_wpf.Services.TextSettingsNavigationService.Close*
  implements:
  - neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
references:
- uid: neo_bpsys_wpf.Services
  commentId: N:neo_bpsys_wpf.Services
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Services
  nameWithType: neo_bpsys_wpf.Services
  fullName: neo_bpsys_wpf.Services
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Services
    name: Services
    href: neo_bpsys_wpf.Services.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Services
    name: Services
    href: neo_bpsys_wpf.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  commentId: T:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  parent: neo_bpsys_wpf.Abstractions.Services
  href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html
  name: ITextSettingsNavigationService
  nameWithType: ITextSettingsNavigationService
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Abstractions.Services
  commentId: N:neo_bpsys_wpf.Abstractions.Services
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Abstractions.Services
  nameWithType: neo_bpsys_wpf.Abstractions.Services
  fullName: neo_bpsys_wpf.Abstractions.Services
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions
    name: Abstractions
    href: neo_bpsys_wpf.Abstractions.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions.Services
    name: Services
    href: neo_bpsys_wpf.Abstractions.Services.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions
    name: Abstractions
    href: neo_bpsys_wpf.Abstractions.html
  - name: .
  - uid: neo_bpsys_wpf.Abstractions.Services
    name: Services
    href: neo_bpsys_wpf.Abstractions.Services.html
- uid: neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl*
  commentId: Overload:neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl
  href: neo_bpsys_wpf.Services.TextSettingsNavigationService.html#neo_bpsys_wpf_Services_TextSettingsNavigationService_SetFrameControl_neo_bpsys_wpf_Enums_FrontWindowType_System_Windows_Controls_Frame_
  name: SetFrameControl
  nameWithType: TextSettingsNavigationService.SetFrameControl
  fullName: neo_bpsys_wpf.Services.TextSettingsNavigationService.SetFrameControl
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  commentId: M:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
  parent: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  isExternal: true
  href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_SetFrameControl_neo_bpsys_wpf_Enums_FrontWindowType_System_Windows_Controls_Frame_
  name: SetFrameControl(FrontWindowType, Frame)
  nameWithType: ITextSettingsNavigationService.SetFrameControl(FrontWindowType, Frame)
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType, System.Windows.Controls.Frame)
  spec.csharp:
  - uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
    name: SetFrameControl
    href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_SetFrameControl_neo_bpsys_wpf_Enums_FrontWindowType_System_Windows_Controls_Frame_
  - name: (
  - uid: neo_bpsys_wpf.Enums.FrontWindowType
    name: FrontWindowType
    href: neo_bpsys_wpf.Enums.FrontWindowType.html
  - name: ','
  - name: " "
  - uid: System.Windows.Controls.Frame
    name: Frame
    isExternal: true
  - name: )
  spec.vb:
  - uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.SetFrameControl(neo_bpsys_wpf.Enums.FrontWindowType,System.Windows.Controls.Frame)
    name: SetFrameControl
    href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_SetFrameControl_neo_bpsys_wpf_Enums_FrontWindowType_System_Windows_Controls_Frame_
  - name: (
  - uid: neo_bpsys_wpf.Enums.FrontWindowType
    name: FrontWindowType
    href: neo_bpsys_wpf.Enums.FrontWindowType.html
  - name: ','
  - name: " "
  - uid: System.Windows.Controls.Frame
    name: Frame
    isExternal: true
  - name: )
- uid: neo_bpsys_wpf.Enums.FrontWindowType
  commentId: T:neo_bpsys_wpf.Enums.FrontWindowType
  parent: neo_bpsys_wpf.Enums
  href: neo_bpsys_wpf.Enums.FrontWindowType.html
  name: FrontWindowType
  nameWithType: FrontWindowType
  fullName: neo_bpsys_wpf.Enums.FrontWindowType
- uid: System.Windows.Controls.Frame
  commentId: T:System.Windows.Controls.Frame
  parent: System.Windows.Controls
  isExternal: true
  name: Frame
  nameWithType: Frame
  fullName: System.Windows.Controls.Frame
- uid: neo_bpsys_wpf.Enums
  commentId: N:neo_bpsys_wpf.Enums
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Enums
  nameWithType: neo_bpsys_wpf.Enums
  fullName: neo_bpsys_wpf.Enums
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Enums
    name: Enums
    href: neo_bpsys_wpf.Enums.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Enums
    name: Enums
    href: neo_bpsys_wpf.Enums.html
- uid: System.Windows.Controls
  commentId: N:System.Windows.Controls
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Windows.Controls
  nameWithType: System.Windows.Controls
  fullName: System.Windows.Controls
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  - name: .
  - uid: System.Windows.Controls
    name: Controls
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.controls
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  - name: .
  - uid: System.Windows.Controls
    name: Controls
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.controls
- uid: neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate*
  commentId: Overload:neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate
  href: neo_bpsys_wpf.Services.TextSettingsNavigationService.html#neo_bpsys_wpf_Services_TextSettingsNavigationService_Navigate_neo_bpsys_wpf_Enums_FrontWindowType_System_Object_
  name: Navigate
  nameWithType: TextSettingsNavigationService.Navigate
  fullName: neo_bpsys_wpf.Services.TextSettingsNavigationService.Navigate
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  commentId: M:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
  parent: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  isExternal: true
  href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Navigate_neo_bpsys_wpf_Enums_FrontWindowType_System_Object_
  name: Navigate(FrontWindowType, object)
  nameWithType: ITextSettingsNavigationService.Navigate(FrontWindowType, object)
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType, object)
  nameWithType.vb: ITextSettingsNavigationService.Navigate(FrontWindowType, Object)
  fullName.vb: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType, Object)
  name.vb: Navigate(FrontWindowType, Object)
  spec.csharp:
  - uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
    name: Navigate
    href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Navigate_neo_bpsys_wpf_Enums_FrontWindowType_System_Object_
  - name: (
  - uid: neo_bpsys_wpf.Enums.FrontWindowType
    name: FrontWindowType
    href: neo_bpsys_wpf.Enums.FrontWindowType.html
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Navigate(neo_bpsys_wpf.Enums.FrontWindowType,System.Object)
    name: Navigate
    href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Navigate_neo_bpsys_wpf_Enums_FrontWindowType_System_Object_
  - name: (
  - uid: neo_bpsys_wpf.Enums.FrontWindowType
    name: FrontWindowType
    href: neo_bpsys_wpf.Enums.FrontWindowType.html
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: neo_bpsys_wpf.Services.TextSettingsNavigationService.Close*
  commentId: Overload:neo_bpsys_wpf.Services.TextSettingsNavigationService.Close
  href: neo_bpsys_wpf.Services.TextSettingsNavigationService.html#neo_bpsys_wpf_Services_TextSettingsNavigationService_Close_neo_bpsys_wpf_Enums_FrontWindowType_
  name: Close
  nameWithType: TextSettingsNavigationService.Close
  fullName: neo_bpsys_wpf.Services.TextSettingsNavigationService.Close
- uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  commentId: M:neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  parent: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService
  href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Close_neo_bpsys_wpf_Enums_FrontWindowType_
  name: Close(FrontWindowType)
  nameWithType: ITextSettingsNavigationService.Close(FrontWindowType)
  fullName: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
  spec.csharp:
  - uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
    name: Close
    href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Close_neo_bpsys_wpf_Enums_FrontWindowType_
  - name: (
  - uid: neo_bpsys_wpf.Enums.FrontWindowType
    name: FrontWindowType
    href: neo_bpsys_wpf.Enums.FrontWindowType.html
  - name: )
  spec.vb:
  - uid: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.Close(neo_bpsys_wpf.Enums.FrontWindowType)
    name: Close
    href: neo_bpsys_wpf.Abstractions.Services.ITextSettingsNavigationService.html#neo_bpsys_wpf_Abstractions_Services_ITextSettingsNavigationService_Close_neo_bpsys_wpf_Enums_FrontWindowType_
  - name: (
  - uid: neo_bpsys_wpf.Enums.FrontWindowType
    name: FrontWindowType
    href: neo_bpsys_wpf.Enums.FrontWindowType.html
  - name: )
