### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.BpWindowTextSettings
  id: BpWindowTextSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress
  - neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints
  - neo_bpsys_wpf.Models.BpWindowTextSettings.MapName
  - neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints
  - neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId
  - neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName
  - neo_bpsys_wpf.Models.BpWindowTextSettings.Timer
  langs:
  - csharp
  - vb
  name: BpWindowTextSettings
  nameWithType: BpWindowTextSettings
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BpWindowTextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 77
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: BP窗口文本设置
  example: []
  syntax:
    content: public class BpWindowTextSettings
    content.vb: Public Class BpWindowTextSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.Timer
  commentId: P:neo_bpsys_wpf.Models.BpWindowTextSettings.Timer
  id: Timer
  parent: neo_bpsys_wpf.Models.BpWindowTextSettings
  langs:
  - csharp
  - vb
  name: Timer
  nameWithType: BpWindowTextSettings.Timer
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.Timer
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Timer
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 79
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings Timer { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property Timer As TextSettings
  overload: neo_bpsys_wpf.Models.BpWindowTextSettings.Timer*
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName
  commentId: P:neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName
  id: TeamName
  parent: neo_bpsys_wpf.Models.BpWindowTextSettings
  langs:
  - csharp
  - vb
  name: TeamName
  nameWithType: BpWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TeamName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 82
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings TeamName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property TeamName As TextSettings
  overload: neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName*
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints
  commentId: P:neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints
  id: MinorPoints
  parent: neo_bpsys_wpf.Models.BpWindowTextSettings
  langs:
  - csharp
  - vb
  name: MinorPoints
  nameWithType: BpWindowTextSettings.MinorPoints
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MinorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 85
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MinorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MinorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints*
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints
  commentId: P:neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints
  id: MajorPoints
  parent: neo_bpsys_wpf.Models.BpWindowTextSettings
  langs:
  - csharp
  - vb
  name: MajorPoints
  nameWithType: BpWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MajorPoints
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 88
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MajorPoints { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MajorPoints As TextSettings
  overload: neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints*
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId
  commentId: P:neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId
  id: PlayerId
  parent: neo_bpsys_wpf.Models.BpWindowTextSettings
  langs:
  - csharp
  - vb
  name: PlayerId
  nameWithType: BpWindowTextSettings.PlayerId
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: PlayerId
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 90
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings PlayerId { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property PlayerId As TextSettings
  overload: neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId*
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.MapName
  commentId: P:neo_bpsys_wpf.Models.BpWindowTextSettings.MapName
  id: MapName
  parent: neo_bpsys_wpf.Models.BpWindowTextSettings
  langs:
  - csharp
  - vb
  name: MapName
  nameWithType: BpWindowTextSettings.MapName
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.MapName
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: MapName
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 93
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings MapName { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property MapName As TextSettings
  overload: neo_bpsys_wpf.Models.BpWindowTextSettings.MapName*
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress
  commentId: P:neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress
  id: GameProgress
  parent: neo_bpsys_wpf.Models.BpWindowTextSettings
  langs:
  - csharp
  - vb
  name: GameProgress
  nameWithType: BpWindowTextSettings.GameProgress
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: GameProgress
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 96
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public TextSettings GameProgress { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.TextSettings
    content.vb: Public Property GameProgress As TextSettings
  overload: neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.Timer*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowTextSettings.Timer
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html#neo_bpsys_wpf_Models_BpWindowTextSettings_Timer
  name: Timer
  nameWithType: BpWindowTextSettings.Timer
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.Timer
- uid: neo_bpsys_wpf.Models.TextSettings
  commentId: T:neo_bpsys_wpf.Models.TextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.TextSettings.html
  name: TextSettings
  nameWithType: TextSettings
  fullName: neo_bpsys_wpf.Models.TextSettings
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html#neo_bpsys_wpf_Models_BpWindowTextSettings_TeamName
  name: TeamName
  nameWithType: BpWindowTextSettings.TeamName
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.TeamName
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html#neo_bpsys_wpf_Models_BpWindowTextSettings_MinorPoints
  name: MinorPoints
  nameWithType: BpWindowTextSettings.MinorPoints
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.MinorPoints
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html#neo_bpsys_wpf_Models_BpWindowTextSettings_MajorPoints
  name: MajorPoints
  nameWithType: BpWindowTextSettings.MajorPoints
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.MajorPoints
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html#neo_bpsys_wpf_Models_BpWindowTextSettings_PlayerId
  name: PlayerId
  nameWithType: BpWindowTextSettings.PlayerId
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.PlayerId
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.MapName*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowTextSettings.MapName
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html#neo_bpsys_wpf_Models_BpWindowTextSettings_MapName
  name: MapName
  nameWithType: BpWindowTextSettings.MapName
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.MapName
- uid: neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress*
  commentId: Overload:neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress
  href: neo_bpsys_wpf.Models.BpWindowTextSettings.html#neo_bpsys_wpf_Models_BpWindowTextSettings_GameProgress
  name: GameProgress
  nameWithType: BpWindowTextSettings.GameProgress
  fullName: neo_bpsys_wpf.Models.BpWindowTextSettings.GameProgress
