### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings
  commentId: T:neo_bpsys_wpf.Models.CutSceneWindowSettings
  id: CutSceneWindowSettings
  parent: neo_bpsys_wpf.Models
  children:
  - neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri
  - neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable
  - neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution
  - neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings
  langs:
  - csharp
  - vb
  name: CutSceneWindowSettings
  nameWithType: CutSceneWindowSettings
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings
  type: Class
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: CutSceneWindowSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 123
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  summary: 过场窗口设置
  example: []
  syntax:
    content: public class CutSceneWindowSettings
    content.vb: Public Class CutSceneWindowSettings
  inheritance:
  - System.Object
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution
  id: Resolution
  parent: neo_bpsys_wpf.Models.CutSceneWindowSettings
  langs:
  - csharp
  - vb
  name: Resolution
  nameWithType: CutSceneWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: Resolution
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 125
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public WindowResolution Resolution { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.WindowResolution
    content.vb: Public Property Resolution As WindowResolution
  overload: neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution*
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable
  id: IsBlackTalentAndTraitEnable
  parent: neo_bpsys_wpf.Models.CutSceneWindowSettings
  langs:
  - csharp
  - vb
  name: IsBlackTalentAndTraitEnable
  nameWithType: CutSceneWindowSettings.IsBlackTalentAndTraitEnable
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: IsBlackTalentAndTraitEnable
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 126
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public bool IsBlackTalentAndTraitEnable { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsBlackTalentAndTraitEnable As Boolean
  overload: neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable*
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri
  id: BgUri
  parent: neo_bpsys_wpf.Models.CutSceneWindowSettings
  langs:
  - csharp
  - vb
  name: BgUri
  nameWithType: CutSceneWindowSettings.BgUri
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: BgUri
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 127
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public string? BgUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BgUri As String
  overload: neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri*
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings
  commentId: P:neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings
  id: TextSettings
  parent: neo_bpsys_wpf.Models.CutSceneWindowSettings
  langs:
  - csharp
  - vb
  name: TextSettings
  nameWithType: CutSceneWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings
  type: Property
  source:
    remote:
      path: neo-bpsys-wpf/Models/Settings.cs
      branch: dev-feat/multiBanMap
      repo: https://github.com/plfjy/neo-bpsys-wpf.git
    id: TextSettings
    path: ../neo-bpsys-wpf/neo-bpsys-wpf/Models/Settings.cs
    startLine: 128
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Models
  syntax:
    content: public CutSceneWindowTextSettings TextSettings { get; set; }
    parameters: []
    return:
      type: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
    content.vb: Public Property TextSettings As CutSceneWindowTextSettings
  overload: neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings*
references:
- uid: neo_bpsys_wpf.Models
  commentId: N:neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Models
  nameWithType: neo_bpsys_wpf.Models
  fullName: neo_bpsys_wpf.Models
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Models
    name: Models
    href: neo_bpsys_wpf.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution
  href: neo_bpsys_wpf.Models.CutSceneWindowSettings.html#neo_bpsys_wpf_Models_CutSceneWindowSettings_Resolution
  name: Resolution
  nameWithType: CutSceneWindowSettings.Resolution
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.Resolution
- uid: neo_bpsys_wpf.Models.WindowResolution
  commentId: T:neo_bpsys_wpf.Models.WindowResolution
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.WindowResolution.html
  name: WindowResolution
  nameWithType: WindowResolution
  fullName: neo_bpsys_wpf.Models.WindowResolution
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable
  href: neo_bpsys_wpf.Models.CutSceneWindowSettings.html#neo_bpsys_wpf_Models_CutSceneWindowSettings_IsBlackTalentAndTraitEnable
  name: IsBlackTalentAndTraitEnable
  nameWithType: CutSceneWindowSettings.IsBlackTalentAndTraitEnable
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.IsBlackTalentAndTraitEnable
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri
  href: neo_bpsys_wpf.Models.CutSceneWindowSettings.html#neo_bpsys_wpf_Models_CutSceneWindowSettings_BgUri
  name: BgUri
  nameWithType: CutSceneWindowSettings.BgUri
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.BgUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings*
  commentId: Overload:neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings
  href: neo_bpsys_wpf.Models.CutSceneWindowSettings.html#neo_bpsys_wpf_Models_CutSceneWindowSettings_TextSettings
  name: TextSettings
  nameWithType: CutSceneWindowSettings.TextSettings
  fullName: neo_bpsys_wpf.Models.CutSceneWindowSettings.TextSettings
- uid: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  commentId: T:neo_bpsys_wpf.Models.CutSceneWindowTextSettings
  parent: neo_bpsys_wpf.Models
  href: neo_bpsys_wpf.Models.CutSceneWindowTextSettings.html
  name: CutSceneWindowTextSettings
  nameWithType: CutSceneWindowTextSettings
  fullName: neo_bpsys_wpf.Models.CutSceneWindowTextSettings
