### YamlMime:ManagedReference
items:
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
  commentId: T:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
  id: TextSettingsEditControl.TaskNotifier`1
  parent: neo_bpsys_wpf.Controls
  children:
  - neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1.op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier{`0})~System.Threading.Tasks.Task{`0}
  langs:
  - csharp
  - vb
  name: TextSettingsEditControl.TaskNotifier<T>
  nameWithType: TextSettingsEditControl.TaskNotifier<T>
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier<T>
  type: Class
  source:
    id: TaskNotifier
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\neo_bpsys_wpf.Controls.TextSettingsEditControl.g.cs
    startLine: 526
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Controls
  summary: A wrapping class that can hold a <xref href="System.Threading.Tasks.Task%601" data-throw-if-not-resolved="false"></xref> value.
  example: []
  syntax:
    content: protected sealed class TextSettingsEditControl.TaskNotifier<T>
    typeParameters:
    - id: T
      description: The type of value for the wrapped <xref href="System.Threading.Tasks.Task%601" data-throw-if-not-resolved="false"></xref> instance.
    content.vb: Protected NotInheritable Class TextSettingsEditControl.TaskNotifier(Of T)
  inheritance:
  - System.Object
  nameWithType.vb: TextSettingsEditControl.TaskNotifier(Of T)
  fullName.vb: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier(Of T)
  name.vb: TextSettingsEditControl.TaskNotifier(Of T)
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1.op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier{`0})~System.Threading.Tasks.Task{`0}
  commentId: M:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1.op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier{`0})~System.Threading.Tasks.Task{`0}
  id: op_Implicit(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier{`0})~System.Threading.Tasks.Task{`0}
  parent: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
  langs:
  - csharp
  - vb
  name: implicit operator Task<T>?(TaskNotifier<T>?)
  nameWithType: TextSettingsEditControl.TaskNotifier<T>.implicit operator Task<T>?(TextSettingsEditControl.TaskNotifier<T>?)
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier<T>.implicit operator System.Threading.Tasks.Task<T>?(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier<T>?)
  type: Operator
  source:
    id: op_Implicit
    path: CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\neo_bpsys_wpf.Controls.TextSettingsEditControl.g.cs
    startLine: 546
  assemblies:
  - neo-bpsys-wpf
  namespace: neo_bpsys_wpf.Controls
  summary: Unwraps the <xref href="System.Threading.Tasks.Task%601" data-throw-if-not-resolved="false"></xref> value stored in the current instance.
  example: []
  syntax:
    content: public static implicit operator Task<T>?(TextSettingsEditControl.TaskNotifier<T>? notifier)
    parameters:
    - id: notifier
      type: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
      description: The input <xref href="neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier%601" data-throw-if-not-resolved="false"></xref> instance.
    return:
      type: System.Threading.Tasks.Task{{T}}
    content.vb: Public Shared Widening Operator CType(notifier As TextSettingsEditControl.TaskNotifier(Of T)) As Task(Of T)
  overload: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1.op_Implicit*
  nameWithType.vb: TextSettingsEditControl.TaskNotifier(Of T).CType(TextSettingsEditControl.TaskNotifier(Of T))
  fullName.vb: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier(Of T).CType(neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier(Of T))
  name.vb: CType(TaskNotifier(Of T))
references:
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: neo_bpsys_wpf.Controls
  commentId: N:neo_bpsys_wpf.Controls
  href: neo_bpsys_wpf.html
  name: neo_bpsys_wpf.Controls
  nameWithType: neo_bpsys_wpf.Controls
  fullName: neo_bpsys_wpf.Controls
  spec.csharp:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Controls
    name: Controls
    href: neo_bpsys_wpf.Controls.html
  spec.vb:
  - uid: neo_bpsys_wpf
    name: neo_bpsys_wpf
    href: neo_bpsys_wpf.html
  - name: .
  - uid: neo_bpsys_wpf.Controls
    name: Controls
    href: neo_bpsys_wpf.Controls.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
  commentId: T:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
  parent: neo_bpsys_wpf.Controls
  href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  name: TextSettingsEditControl.TaskNotifier<T>
  nameWithType: TextSettingsEditControl.TaskNotifier<T>
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier<T>
  nameWithType.vb: TextSettingsEditControl.TaskNotifier(Of T)
  fullName.vb: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier(Of T)
  name.vb: TextSettingsEditControl.TaskNotifier(Of T)
  spec.csharp:
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl
    name: TextSettingsEditControl
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  - name: .
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
    name: TaskNotifier
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl
    name: TextSettingsEditControl
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.html
  - name: .
  - uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1
    name: TaskNotifier
    href: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1.op_Implicit*
  commentId: Overload:neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier`1.op_Implicit
  name: implicit operator
  nameWithType: TextSettingsEditControl.TaskNotifier<T>.implicit operator
  fullName: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier<T>.implicit operator
  nameWithType.vb: TextSettingsEditControl.TaskNotifier(Of T).CType
  fullName.vb: neo_bpsys_wpf.Controls.TextSettingsEditControl.TaskNotifier(Of T).CType
  name.vb: CType
  spec.csharp:
  - name: implicit
  - name: " "
  - name: operator
- uid: System.Threading.Tasks.Task{{T}}
  commentId: T:System.Threading.Tasks.Task{``0}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<T>
  nameWithType: Task<T>
  fullName: System.Threading.Tasks.Task<T>
  nameWithType.vb: Task(Of T)
  fullName.vb: System.Threading.Tasks.Task(Of T)
  name.vb: Task(Of T)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
