name: Pages

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Setup Git
              shell: pwsh
              run: |
                git config --global user.name "gitHub-actions"
                git config --global user.email "action@github.com"
                    
            - name: clone neo-bpsys-wpf
              shell: pwsh
              run: |
                git clone --depth=1 https://github.com/PLFJY/neo-bpsys-wpf ../neo-bpsys-wpf 

            - name: Generate docsite
              shell: pwsh
              run: |
                ls
                ls ..
                ls ../neo-bpsys-wpf

            - name: Install .NET Core
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x

            - name: Install docfx
              shell: pwsh
              run: dotnet tool install -g docfx
            
            - name: Generate docsite
              shell: pwsh
              run: |
                cd ${{ github.workspace }}
                docfx docfx.json
