name: Pages

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: clone neo-bpsys-wpf
              shell: pwsh
              run: |
                git clone --depth=1 https://github.com/PLFJY/neo-bpsys-wpf ../neo-bpsys-wpf

            - name: Install .NET Core
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x

            - name: Install docfx
              shell: pwsh
              run: dotnet tool install -g docfx
            
            - name: Generate doc site
              shell: pwsh
              run: |
                cd ${{ github.workspace }}
                docfx docfx.json

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./_site
